let k;
let j = 3; 
a = 0;
console.log(a);
k = j == 3;
console.log(k);
j = 2 * k - 7 <= j - 8;
console.log(j);
a = k % 2 > j && a != 3;
console.log(a);
k = !(a - j);
console.log(k);
a = !a + k;
console.log(a);
a *= 3 + 6 % 3;
console.log(a);
k += j < 5 && a != 0 && k > 5 || j < a;
j = !a * !0;
console.log(j);
a = !((!j == 1 || k < 2) && a < 3);
console.log(a);
k = a / a && !j && a || k * 3 > !!j;
console.log(k);
j = a * 3 + k % 2 - 3 / (0 || a > j);
console.log(j);